export const Colors = {
  BACKGROUND_COLOR: '#BFCAFF',
  BACKGROUND_STROKE_COLOR: '#00125A',

  WHITE: '#FFFFFF',
  LIGHT_GREY: '#DFDFDF',
  DARK_GREY: '#36303F',
  BLACK: '#000000',

  PURPLE: '#7100CD',
  LIGHT_PURPLE: '#005BD2',

  DULL_YELLOW: `#FCD259ff`,

  ACTIVE_BUTTON: '#2C2C2C',
  IN_ACTIVE_BUTTON: '#DCDCDC',

  SKY_BLUE: '#0099cc',
};
